# Generated by Django 2.2.7 on 2020-04-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200404_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('wears', 'Wears'), ('real_estate', 'Real Estate'), ('fashion', 'Fashion'), ('gadgets', 'Gadgets')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
