# Generated by Django 2.2.7 on 2020-04-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='appartment_address',
            new_name='apartment_address',
        ),
    ]
